In [1]:
import pandas as pd

data = {
    "Имя": ["Анна", "Иван", "Ольга"],
    "Возраст": [25, 30, 22]
}

df = pd.DataFrame(data)
df["Город"] = ["Москва", "СПб", "Казань"]

print(df)

     Имя  Возраст   Город
0   Анна       25  Москва
1   Иван       30     СПб
2  Ольга       22  Казань

In [2]:
df["Страна"] = "Россия"
print(df)

     Имя  Возраст   Город  Страна
0   Анна       25  Москва  Россия
1   Иван       30     СПб  Россия
2  Ольга       22  Казань  Россия

In [3]:
df["Возраст_в_месяцах"] = df["Возраст"] * 12
print(df)

     Имя  Возраст   Город  Страна  Возраст_в_месяцах
0   Анна       25  Москва  Россия                300
1   Иван       30     СПб  Россия                360
2  Ольга       22  Казань  Россия                264

In [4]:
df = df.assign(Зарплата=[50000, 60000, 45000])
print(df)

     Имя  Возраст   Город  Страна  Возраст_в_месяцах  Зарплата
0   Анна       25  Москва  Россия                300     50000
1   Иван       30     СПб  Россия                360     60000
2  Ольга       22  Казань  Россия                264     45000

In [5]:
df["Категория возраста"] = df["Возраст"].apply(lambda x: "Молодой" if x < 30 else "Взрослый")
print(df)

     Имя  Возраст   Город  Страна  Возраст_в_месяцах  Зарплата  \
0   Анна       25  Москва  Россия                300     50000
1   Иван       30     СПб  Россия                360     60000
2  Ольга       22  Казань  Россия                264     45000

  Категория возраста
0            Молодой
1           Взрослый
2            Молодой

In [7]:
df.loc[3] = ["Петр", 40, "Новосибирск", "Россия", 480, 85000, "Взрослый"]
print(df)

     Имя  Возраст        Город  Страна  Возраст_в_месяцах  Зарплата  \
0   Анна       25       Москва  Россия                300     50000
1   Иван       30          СПб  Россия                360     60000
2  Ольга       22       Казань  Россия                264     45000
3   Петр       40  Новосибирск  Россия                480     85000

  Категория возраста
0            Молодой
1           Взрослый
2            Молодой
3           Взрослый

In [9]:
new_row = pd.DataFrame([{"Имя": "Сергей", "Возраст": 35, "Город": "Сочи", "Страна": "Россия"}])
df = pd.concat([df, new_row], ignore_index=True)
print(df)

      Имя  Возраст        Город  Страна  Возраст_в_месяцах  Зарплата  \
0    Анна       25       Москва  Россия              300.0   50000.0
1    Иван       30          СПб  Россия              360.0   60000.0
2   Ольга       22       Казань  Россия              264.0   45000.0
3    Петр       40  Новосибирск  Россия              480.0   85000.0
4  Сергей       35         Сочи  Россия                NaN       NaN

  Категория возраста
0            Молодой
1           Взрослый
2            Молодой
3           Взрослый
4                NaN

In [10]:
new_data = pd.DataFrame([{"Имя": "Алексей", "Возраст": 29, "Город": "Томск", "Страна": "Россия"}])

df = pd.concat([df, new_data], ignore_index=True)
print(df)

       Имя  Возраст        Город  Страна  Возраст_в_месяцах  Зарплата  \
0     Анна       25       Москва  Россия              300.0   50000.0
1     Иван       30          СПб  Россия              360.0   60000.0
2    Ольга       22       Казань  Россия              264.0   45000.0
3     Петр       40  Новосибирск  Россия              480.0   85000.0
4   Сергей       35         Сочи  Россия                NaN       NaN
5  Алексей       29        Томск  Россия                NaN       NaN

  Категория возраста
0            Молодой
1           Взрослый
2            Молодой
3           Взрослый
4                NaN
5                NaN

In [11]:
new_rows = pd.DataFrame([
    {"Имя": "Дмитрий", "Возраст": 31, "Город": "Самара", "Страна": "Россия"},
    {"Имя": "Елена", "Возраст": 27, "Город": "Воронеж", "Страна": "Россия"}
])

df = pd.concat([df, new_rows], ignore_index=True)
print(df)

       Имя  Возраст        Город  Страна  Возраст_в_месяцах  Зарплата  \
0     Анна       25       Москва  Россия              300.0   50000.0
1     Иван       30          СПб  Россия              360.0   60000.0
2    Ольга       22       Казань  Россия              264.0   45000.0
3     Петр       40  Новосибирск  Россия              480.0   85000.0
4   Сергей       35         Сочи  Россия                NaN       NaN
5  Алексей       29        Томск  Россия                NaN       NaN
6  Дмитрий       31       Самара  Россия                NaN       NaN
7    Елена       27      Воронеж  Россия                NaN       NaN

  Категория возраста
0            Молодой
1           Взрослый
2            Молодой
3           Взрослый
4                NaN
5                NaN
6                NaN
7                NaN

In [14]:
df.loc["новый"] = {"Имя": "Артем", "Возраст": 33, "Город": "Калуга"}
print(df)

         Имя  Возраст   Город
0       Анна       25  Москва
1       Иван       30     СПб
2      Ольга       22  Казань
новый  Артем       33  Калуга

In [13]:
import pandas as pd

data = {
    "Имя": ["Анна", "Иван", "Ольга"],
    "Возраст": [25, 30, 22],
    "Город": ["Москва", "СПб", "Казань"],
    "Зарплата": [50000, 60000, 45000]
}

df = pd.DataFrame(data)

df = df.drop(columns=["Зарплата"])
print(df)

     Имя  Возраст   Город
0   Анна       25  Москва
1   Иван       30     СПб
2  Ольга       22  Казань

In [15]:
df = df.drop(columns=['Возраст', 'Город'])
print(df)

         Имя
0       Анна
1       Иван
2      Ольга
новый  Артем

In [16]:
del df["Имя"]
print(df)

Empty DataFrame
Columns: []
Index: [0, 1, 2, новый]

In [18]:
df = pd.DataFrame(data)
df = df.drop(index=1)
print(df)

     Имя  Возраст   Город  Зарплата
0   Анна       25  Москва     50000
2  Ольга       22  Казань     45000

In [19]:
df = df.drop(index=[0, 2])
print(df)

Empty DataFrame
Columns: [Имя, Возраст, Город, Зарплата]
Index: []

In [20]:
df = pd.DataFrame(data)
df = df[df["Возраст"] > 25]
print(df)

    Имя  Возраст Город  Зарплата
1  Иван       30   СПб     60000

In [21]:
df = df.reset_index(drop=True)
print(df)

    Имя  Возраст Город  Зарплата
0  Иван       30   СПб     60000

In [22]:
df.loc[3] = ["Мария", None, "Самара", 55000]
df = df.dropna()
print(df)

    Имя Возраст Город  Зарплата
0  Иван      30   СПб     60000

In [23]:
df = pd.DataFrame({
    "Имя": ["Анна", "Иван", "Анна", "Ольга"],
    "Возраст": [25, 30, 25, 22]
})

df = df.drop_duplicates()
print(df)

     Имя  Возраст
0   Анна       25
1   Иван       30
3  Ольга       22

In [24]:
df = df.drop_duplicates(subset=['Имя'])

In [25]:
import pandas as pd

data = {
    "Имя": ["Анна", "Иван", "Ольга", "Петр", "Мария"],
    "Возраст": [25, 30, 22, 40, 35],
    "Город": ["Москва", "СПб", "Казань", "Новосибирск", "СПб"],
    "Зарплата": [50000, 60000, 45000, 70000, 65000]
}

df = pd.DataFrame(data)
print(df)

     Имя  Возраст        Город  Зарплата
0   Анна       25       Москва     50000
1   Иван       30          СПб     60000
2  Ольга       22       Казань     45000
3   Петр       40  Новосибирск     70000
4  Мария       35          СПб     65000

In [26]:
df_filtered = df.query("Возраст > 30")
print(df_filtered)

     Имя  Возраст        Город  Зарплата
3   Петр       40  Новосибирск     70000
4  Мария       35          СПб     65000

In [27]:
df_filtered = df.query("Город == 'СПб' and Зарплата > 60000")
print(df_filtered)

     Имя  Возраст Город  Зарплата
4  Мария       35   СПб     65000

In [28]:
min_age = 25
df_filtered = df.query("Возраст > @min_age")
print(df_filtered)

     Имя  Возраст        Город  Зарплата
1   Иван       30          СПб     60000
3   Петр       40  Новосибирск     70000
4  Мария       35          СПб     65000

In [29]:
df_filtered = df[df["Город"].isin(["Москва", "СПб"])]
print(df_filtered)

     Имя  Возраст   Город  Зарплата
0   Анна       25  Москва     50000
1   Иван       30     СПб     60000
4  Мария       35     СПб     65000

In [30]:
df_filtered = df[~df["Город"].isin(["Москва", "СПб"])]
print(df_filtered)

     Имя  Возраст        Город  Зарплата
2  Ольга       22       Казань     45000
3   Петр       40  Новосибирск     70000

In [31]:
df_filtered = df[df["Возраст"].between(25, 35)]
print(df_filtered)

     Имя  Возраст   Город  Зарплата
0   Анна       25  Москва     50000
1   Иван       30     СПб     60000
4  Мария       35     СПб     65000

In [32]:
df_filtered = df[df["Возраст"].between(25, 35, inclusive="neither")]
print(df_filtered)

    Имя  Возраст Город  Зарплата
1  Иван       30   СПб     60000

In [33]:
import pandas as pd

data = {
    "Имя": ["Анна", "Иван", "Ольга", "Петр", None],
    "Возраст": [25, 30, 22, None, 35],
    "Город": ["Москва", "СПб", "Казань", "Новосибирск", "СПб"]
}

df = pd.DataFrame(data)
print(df)

     Имя  Возраст        Город
0   Анна     25.0       Москва
1   Иван     30.0          СПб
2  Ольга     22.0       Казань
3   Петр      NaN  Новосибирск
4    NaN     35.0          СПб

In [34]:
print(df.count())

Имя        4
Возраст    4
Город      5
dtype: int64

In [35]:
print(df["Город"].value_counts())

Город
СПб            2
Москва         1
Казань         1
Новосибирск    1
Name: count, dtype: int64

In [36]:
print(df["Город"].value_counts(sort=False))

print(df["Имя"].value_counts(dropna=False))

Город
Москва         1
СПб            2
Казань         1
Новосибирск    1
Name: count, dtype: int64
Имя
Анна     1
Иван     1
Ольга    1
Петр     1
NaN      1
Name: count, dtype: int64

In [37]:
print(df.nunique())

Имя        4
Возраст    4
Город      4
dtype: int64

In [38]:
print(df["Имя"].nunique(dropna=False))

5

In [39]:
print(df.isna().sum())

Имя        1
Возраст    1
Город      0
dtype: int64

In [40]:
import pandas as pd

data = {
    "Имя": ["Анна", "Иван", "Ольга", "Петр", "Мария"],
    "Возраст": [25, 30, 22, 40, 35],
    "Зарплата": [50000, 60000, 45000, 70000, 65000]
}

df = pd.DataFrame(data)
print(df)

     Имя  Возраст  Зарплата
0   Анна       25     50000
1   Иван       30     60000
2  Ольга       22     45000
3   Петр       40     70000
4  Мария       35     65000

In [41]:
df_sorted = df.sort_values(by="Возраст")
print(df_sorted)

     Имя  Возраст  Зарплата
2  Ольга       22     45000
0   Анна       25     50000
1   Иван       30     60000
4  Мария       35     65000
3   Петр       40     70000

In [42]:
df_sorted = df.sort_values(by="Возраст", ascending=False)
print(df_sorted)

     Имя  Возраст  Зарплата
3   Петр       40     70000
4  Мария       35     65000
1   Иван       30     60000
0   Анна       25     50000
2  Ольга       22     45000

In [43]:
df_sorted = df.sort_values(by=["Возраст", "Зарплата"], ascending=[True, False])
print(df_sorted)

     Имя  Возраст  Зарплата
2  Ольга       22     45000
0   Анна       25     50000
1   Иван       30     60000
4  Мария       35     65000
3   Петр       40     70000

In [44]:
df.loc[5] = ["Елена", None, 55000]
df_sorted = df.sort_values(by="Возраст", na_position="first")
print(df_sorted)

     Имя Возраст  Зарплата
5  Елена    None     55000
2  Ольга      22     45000
0   Анна      25     50000
1   Иван      30     60000
4  Мария      35     65000
3   Петр      40     70000

In [45]:
df_sorted = df.sort_index()
print(df_sorted)

     Имя Возраст  Зарплата
0   Анна      25     50000
1   Иван      30     60000
2  Ольга      22     45000
3   Петр      40     70000
4  Мария      35     65000
5  Елена    None     55000

In [46]:
df_sorted = df.sort_index(ascending=False)
print(df_sorted)

     Имя Возраст  Зарплата
5  Елена    None     55000
4  Мария      35     65000
3   Петр      40     70000
2  Ольга      22     45000
1   Иван      30     60000
0   Анна      25     50000

In [47]:
import pandas as pd

df = pd.DataFrame({
    "Имя": ["Анна", "Иван", "Ольга"],
    "Возраст": [25, 30, 22],
    "Город": ["Москва", "СПб", "Казань"]
})

print(df)

     Имя  Возраст   Город
0   Анна       25  Москва
1   Иван       30     СПб
2  Ольга       22  Казань

In [48]:
from IPython.display import display
display(df)

     Имя  Возраст   Город
0   Анна       25  Москва
1   Иван       30     СПб
2  Ольга       22  Казань

In [49]:
df.head(5)

df.tail(3)

     Имя  Возраст   Город
0   Анна       25  Москва
1   Иван       30     СПб
2  Ольга       22  Казань

In [50]:
pd.set_option("display.max_rows", 100)

pd.set_option("display.max_columns", 50)

pd.set_option("display.max_colwidth", None)

In [51]:
pd.set_option("display.float_format", "{:.2f}".format)

df.style.set_sticky()

In [52]:
pip install qgrid

Collecting qgrid
  Downloading qgrid-1.3.1.tar.gz (889 kB)
     ---------------------------------------- 0.0/889.2 kB ? eta -:--:--
     -------------------------------- ---- 786.4/889.2 kB 32.4 MB/s eta 0:00:01
     ---------------------------------------- 889.2/889.2 kB 2.1 MB/s  0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: notebook>=4.0.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from qgrid) (7.5.6)
Requirement already satisfied: pandas>=0.18.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from qgrid) (3.0.3)
Requirement already satisfied: ipywidgets>=7.0.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from qgrid) (8.1.8)
Requirement already satisfied: comm>=0.1.3 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from ipywidgets>=7.0.0->qgrid) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from ipywidgets>=7.0.0->qgrid) (9.13.0)
Requirement already satisfied: traitlets>=4.3.1 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from ipywidgets>=7.0.0->qgrid) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from ipywidgets>=7.0.0->qgrid) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from ipywidgets>=7.0.0->qgrid) (3.0.16)
Requirement already satisfied: colorama>=0.4.4 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->qgrid) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->qgrid) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->qgrid) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->qgrid) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.6 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->qgrid) (0.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->qgrid) (3.0.52)
Requirement already satisfied: psutil>=7 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->qgrid) (7.2.2)
Requirement already satisfied: pygments>=2.14.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->qgrid) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->qgrid) (0.6.3)
Requirement already satisfied: wcwidth in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets>=7.0.0->qgrid) (0.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jedi>=0.18.2->ipython>=6.1.0->ipywidgets>=7.0.0->qgrid) (0.8.6)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from notebook>=4.0.0->qgrid) (2.17.0)
Requirement already satisfied: jupyterlab-server<3,>=2.28.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from notebook>=4.0.0->qgrid) (2.28.0)
Requirement already satisfied: jupyterlab<4.6,>=4.5.7 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from notebook>=4.0.0->qgrid) (4.5.7)
Requirement already satisfied: notebook-shim<0.3,>=0.2 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from notebook>=4.0.0->qgrid) (0.2.4)
Requirement already satisfied: tornado>=6.2.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from notebook>=4.0.0->qgrid) (6.5.5)
Requirement already satisfied: anyio>=3.1.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (4.13.0)
Requirement already satisfied: argon2-cffi>=21.1 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (25.1.0)
Requirement already satisfied: jinja2>=3.0.3 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (3.1.6)
Requirement already satisfied: jupyter-client>=7.4.4 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (8.8.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (5.9.1)
Requirement already satisfied: jupyter-events>=0.11.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (0.12.1)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (0.5.4)
Requirement already satisfied: nbconvert>=6.4.4 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (7.17.1)
Requirement already satisfied: nbformat>=5.3.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (5.10.4)
Requirement already satisfied: packaging>=22.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (26.2)
Requirement already satisfied: prometheus-client>=0.9 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (0.25.0)
Requirement already satisfied: pywinpty>=2.0.1 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (3.0.3)
Requirement already satisfied: pyzmq>=24 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (27.1.0)
Requirement already satisfied: send2trash>=1.8.2 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (1.9.0)
Requirement already satisfied: async-lru>=1.0.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jupyterlab<4.6,>=4.5.7->notebook>=4.0.0->qgrid) (2.3.0)
Requirement already satisfied: httpx<1,>=0.25.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jupyterlab<4.6,>=4.5.7->notebook>=4.0.0->qgrid) (0.28.1)
Requirement already satisfied: ipykernel!=6.30.0,>=6.5.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jupyterlab<4.6,>=4.5.7->notebook>=4.0.0->qgrid) (7.2.0)
Requirement already satisfied: jupyter-lsp>=2.0.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jupyterlab<4.6,>=4.5.7->notebook>=4.0.0->qgrid) (2.3.1)
Requirement already satisfied: setuptools>=41.1.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jupyterlab<4.6,>=4.5.7->notebook>=4.0.0->qgrid) (82.0.1)
Requirement already satisfied: certifi in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from httpx<1,>=0.25.0->jupyterlab<4.6,>=4.5.7->notebook>=4.0.0->qgrid) (2026.4.22)
Requirement already satisfied: httpcore==1.* in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from httpx<1,>=0.25.0->jupyterlab<4.6,>=4.5.7->notebook>=4.0.0->qgrid) (1.0.9)
Requirement already satisfied: idna in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from httpx<1,>=0.25.0->jupyterlab<4.6,>=4.5.7->notebook>=4.0.0->qgrid) (3.13)
Requirement already satisfied: h11>=0.16 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab<4.6,>=4.5.7->notebook>=4.0.0->qgrid) (0.16.0)
Requirement already satisfied: babel>=2.10 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jupyterlab-server<3,>=2.28.0->notebook>=4.0.0->qgrid) (2.18.0)
Requirement already satisfied: json5>=0.9.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jupyterlab-server<3,>=2.28.0->notebook>=4.0.0->qgrid) (0.14.0)
Requirement already satisfied: jsonschema>=4.18.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jupyterlab-server<3,>=2.28.0->notebook>=4.0.0->qgrid) (4.26.0)
Requirement already satisfied: requests>=2.31 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jupyterlab-server<3,>=2.28.0->notebook>=4.0.0->qgrid) (2.33.1)
Requirement already satisfied: argon2-cffi-bindings in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (25.1.0)
Requirement already satisfied: debugpy>=1.6.5 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.7->notebook>=4.0.0->qgrid) (1.8.20)
Requirement already satisfied: nest-asyncio>=1.4 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.7->notebook>=4.0.0->qgrid) (1.6.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jinja2>=3.0.3->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->notebook>=4.0.0->qgrid) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->notebook>=4.0.0->qgrid) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->notebook>=4.0.0->qgrid) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->notebook>=4.0.0->qgrid) (0.30.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jupyter-client>=7.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jupyter-core!=5.0.*,>=4.12->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (4.9.6)
Requirement already satisfied: python-json-logger>=2.0.4 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (4.1.0)
Requirement already satisfied: pyyaml>=5.3 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (6.0.3)
Requirement already satisfied: rfc3339-validator in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (0.1.1)
Requirement already satisfied: fqdn in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (1.5.1)
Requirement already satisfied: isoduration in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (3.1.1)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (1.1.0)
Requirement already satisfied: uri-template in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (25.10.0)
Requirement already satisfied: beautifulsoup4 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (4.14.3)
Requirement already satisfied: bleach!=5.0.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (6.3.0)
Requirement already satisfied: defusedxml in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (3.2.0)
Requirement already satisfied: nbclient>=0.5.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (0.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (1.5.1)
Requirement already satisfied: webencodings in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (1.4.0)
Requirement already satisfied: fastjsonschema>=2.15 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (2.21.2)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from pandas>=0.18.0->qgrid) (2.4.4)
Requirement already satisfied: tzdata in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from pandas>=0.18.0->qgrid) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->jupyter-client>=7.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->notebook>=4.0.0->qgrid) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->notebook>=4.0.0->qgrid) (2.6.3)
Requirement already satisfied: lark>=1.2.2 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (1.3.1)
Requirement already satisfied: executing>=1.2.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets>=7.0.0->qgrid) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets>=7.0.0->qgrid) (3.0.1)
Requirement already satisfied: pure-eval in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets>=7.0.0->qgrid) (0.2.3)
Requirement already satisfied: cffi>=1.0.1 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (2.0.0)
Requirement already satisfied: pycparser in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (3.0)
Requirement already satisfied: soupsieve>=1.6.1 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (4.15.0)
Requirement already satisfied: arrow>=0.15.0 in C:\Users\user\AppData\Roaming\Python\Python313\site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (1.4.0)
Building wheels for collected packages: qgrid
  Building wheel for qgrid (pyproject.toml): started
  Building wheel for qgrid (pyproject.toml): finished with status 'done'
  Created wheel for qgrid: filename=qgrid-1.3.1-py2.py3-none-any.whl size=1761358 sha256=387b5d8856211377afa410fb1ce9fd5faba7ebbd47e3f2cc4fd2a84d584fa9cc
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\c5\d6\94\90a1a7d17c7ff23f87b50dfeca896fd95f3f11a401537205da
Successfully built qgrid
Installing collected packages: qgrid
Successfully installed qgrid-1.3.1
Note: you may need to restart the kernel to use updated packages.

In [ ]:
from tabulate import tabulate
print(tabulate(df, headers="keys", tablefmt="github"))

In [54]:
df.style.set_properties(**{"background-color": "lightgray", "color": "black"})

html_table = df.to_html()
with open("table.html", "w", encoding="utf-8") as f:
    f.write(html_table)